% Filename: stew.m
% Author: Joe Brown, California State University, Sacramento  8/04/2006
% Description: This file contains a function to carry out GUI operation of the closed form forward kinematics analysis program for the 6-DOF CDSL Stewart platform.

function stewsolve(fcn)
clc
if nargin == 0
    fcn = 'stew';
end
switch fcn

case 'stew'%this is the initial case, which is the figure set up and initialization of all the GUI elements.
    
    plotinfo.myname = mfilename;
    %--------------------------------------------------------------Main Window
    fig = figure('Position',centerfig(600,600),...
    'Resize','off',...
    'NumberTitle','off',...
    'Name','Stewart Platform Kinematics Solver',...
    'Interruptible','off',...
    'Menubar','none',...
    'Color',get(0,'DefaultUIControlBackgroundColor'));
    %------------------------------------------------------------------Axes
    plotinfo.ax = axes('Units','pixels',...
        'Position',[170 50 350 350],...
        'Visible','off');
    %-----------------------------------------------------------Entry Boxes
    %----------Base coordinates
    uicontrol(gcf,'Style','text','String','xsi','Position',[70,588,20,10]);
    uicontrol(gcf,'Style','text','String','ysi','Position',[125,586,20,12]);
    uicontrol(gcf,'Style','text','String','Base 1:','Position',[5,567,50,10]);
        plotinfo.base1x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,560,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
        plotinfo.base1y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[110,560,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
    uicontrol(gcf,'Style','text','String','Base 2:','Position',[5,542,50,10]);
        plotinfo.base2x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,535,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
        plotinfo.base2y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[110,535,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
    uicontrol(gcf,'Style','text','String','Base 3:','Position',[5,517,50,10]);
        plotinfo.base3x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,510,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
        plotinfo.base3y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[110,510,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
    uicontrol(gcf,'Style','text','String','Base 4:','Position',[5,492,50,10]);
        plotinfo.base4x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,485,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
        plotinfo.base4y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[110,485,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
    uicontrol(gcf,'Style','text','String','Base 5:','Position',[5,467,50,10]);
        plotinfo.base5x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,460,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
        plotinfo.base5y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[110,460,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
    uicontrol(gcf,'Style','text','String','Base 6:','Position',[5,442,50,10]);
        plotinfo.base6x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,435,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);
        plotinfo.base6y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[110,435,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' base']);

    %---------------platform coordinates
    uicontrol(gcf,'Style','text','String','xmi','Position',[270,588,20,10]);
    uicontrol(gcf,'Style','text','String','ymi','Position',[325,586,20,12]);
    uicontrol(gcf,'Style','text','String','Platform 1:','Position',[200,567,50,10]);
        plotinfo.plat1x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[255,560,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
        plotinfo.plat1y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[310,560,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
    uicontrol(gcf,'Style','text','String','Platform 2:','Position',[200,542,50,10]);
        plotinfo.plat2x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[255,535,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
        plotinfo.plat2y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[310,535,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
    uicontrol(gcf,'Style','text','String','Platform 3:','Position',[200,517,50,10]);
        plotinfo.plat3x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[255,510,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
        plotinfo.plat3y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[310,510,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
    uicontrol(gcf,'Style','text','String','Platform 4:','Position',[200,492,50,10]);
        plotinfo.plat4x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[255,485,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
        plotinfo.plat4y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[310,485,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
    uicontrol(gcf,'Style','text','String','Platform 5:','Position',[200,467,50,10]);
        plotinfo.plat5x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[255,460,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
        plotinfo.plat5y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[310,460,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
    uicontrol(gcf,'Style','text','String','Platform 6:','Position',[200,442,50,10]);
        plotinfo.plat6x=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[255,435,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);
        plotinfo.plat6y=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[310,435,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' plat']);

    %---------------Constraints
    uicontrol(gcf,'Style','text','String','Constraints','Position',[410,588,65,10]);
    uicontrol(gcf,'Style','text','String','min','Position',[490,588,20,10]);
    uicontrol(gcf,'Style','text','String','max','Position',[546,588,20,10]);
    uicontrol(gcf,'Style','text','String','Roll(x):','Position',[420,567,50,12]);
        plotinfo.rollmin=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[475,560,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
        plotinfo.rollmax=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[530,560,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
    uicontrol(gcf,'Style','text','String','Pitch(y):','Position',[420,542,50,12]);
        plotinfo.pitchmin=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[475,535,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
        plotinfo.pitchmax=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[530,535,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
    uicontrol(gcf,'Style','text','String','Yaw(z):','Position',[420,517,50,12]);
        plotinfo.yawmin=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[475,510,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
        plotinfo.yawmax=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[530,510,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
    uicontrol(gcf,'Style','text','String','X:','Position',[420,492,50,10]);
        plotinfo.pxmin=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[475,485,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
        plotinfo.pxmax=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[530,485,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
    uicontrol(gcf,'Style','text','String','Y:','Position',[420,467,50,10]);
        plotinfo.pymin=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[475,460,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
        plotinfo.pymax=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[530,460,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
    uicontrol(gcf,'Style','text','String','Z:','Position',[420,442,50,10]);
        plotinfo.pzmin=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[475,435,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);
        plotinfo.pzmax=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[530,435,50,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' constraints']);

    %-------------------Leg lengths
    uicontrol(gcf,'Style','text','String','Leg 1:','Position',[5,388,50,15]);
        plotinfo.leg1=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,385,70,20],...
        'BackgroundColor',[.8,1,1], ...
        'CallBack',[plotinfo.myname,' legs']);
    uicontrol(gcf,'Style','text','String','Leg 2:','Position',[5,362,50,15]);
        plotinfo.leg2=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,360,70,20],...
        'BackgroundColor',[.8,1,1], ...
        'CallBack',[plotinfo.myname,' legs']);
    uicontrol(gcf,'Style','text','String','Leg 3:','Position',[5,338,50,15]);
        plotinfo.leg3=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,335,70,20],...
        'BackgroundColor',[.8,1,1], ...
        'CallBack',[plotinfo.myname,' legs']);
    uicontrol(gcf,'Style','text','String','Leg 4:','Position',[5,313,50,15]);
        plotinfo.leg4=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,310,70,20],...
        'BackgroundColor',[.8,1,1], ...
        'CallBack',[plotinfo.myname,' legs']);
    uicontrol(gcf,'Style','text','String','Leg 5:','Position',[5,288,50,15]);
        plotinfo.leg5=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,285,70,20],...
        'BackgroundColor',[.8,1,1], ...
        'CallBack',[plotinfo.myname,' legs']);
    uicontrol(gcf,'Style','text','String','Leg 6:','Position',[5,263,50,15]);
        plotinfo.leg6=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,260,70,20],...
        'BackgroundColor',[.8,1,1], ...
        'CallBack',[plotinfo.myname,' legs']);
    
    %-------------------Angles and position of table                 
    uicontrol(gcf,'Style','text','String','Roll(x):','Position',[5,192,50,12]);
        plotinfo.roll=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,185,70,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' tablepos']);
    uicontrol(gcf,'Style','text','String','Pitch(y):','Position',[5,167,50,12]);
        plotinfo.pitch=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,160,70,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' tablepos']);
    uicontrol(gcf,'Style','text','String','Yaw(z):','Position',[5,142,50,12]);
        plotinfo.yaw=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,135,70,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' tablepos']);
    uicontrol(gcf,'Style','text','String','X:','Position',[5,117,50,10]);
        plotinfo.Pxval=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,110,70,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' tablepos']);
    uicontrol(gcf,'Style','text','String','Y:','Position',[5,92,50,10]);
        plotinfo.Pyval=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,85,70,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' tablepos']);
    uicontrol(gcf,'Style','text','String','Z:','Position',[5,67,50,10]);
        plotinfo.Pzval=uicontrol(gcf,'Style','edit', ...
        'String','0',...
        'Position',[55,60,70,20],...
        'BackgroundColor',[1,1,1], ...
        'CallBack',[plotinfo.myname,' tablepos']);

    %------------------------------------------------------------Quit button
    uicontrol('Style','pushbutton',...
        'Position',[540,10,45,25],...
        'String','Quit',...
        'Interruptible','off',...
        'BusyAction','cancel',...
        'Callback',[plotinfo.myname,' quit']);
    %-------------------------------------------------------save button
        plotinfo.save_me=uicontrol('Style','pushbutton',...
        'Position',[540,40,45,25],...
        'String','Save',...
        'Interruptible','off',...
        'BusyAction','cancel',...
        'Callback',[plotinfo.myname,' save_me']);
    %-------------------------------------------------------Solve Forward
    plotinfo.sol_for=uicontrol('Style','pushbutton',...
        'Position',[45,220,85,25],...
        'String','Solve Forward',...
        'Interruptible','off',...
        'BusyAction','cancel',...
        'Callback',[plotinfo.myname,' solve_for']);
    %-------------------------------------------------------Solve Inverse
    plotinfo.sol_inv=uicontrol('Style','pushbutton',...
        'Position',[45,20,85,25],...
        'String','Solve Inverse',...
        'Interruptible','off',...
        'BusyAction','cancel',...
        'Callback',[plotinfo.myname,' solve_inv']);
    %-------------------------------------------------------solution buttons
    plotinfo.prevsol=uicontrol('Style','pushbutton',...
        'Position',[290,10,25,20],...
        'String','<<',...
        'Visible','off',...
        'Interruptible','off',...
        'BusyAction','cancel',...
        'Callback',[plotinfo.myname,' prevsol']);
    plotinfo.solutions_text=uicontrol(gcf,'Style','text','String',' ','Position',[315,17,70,10],'Visible','off');
    plotinfo.nextsol=uicontrol('Style','pushbutton',...
        'Position',[380,10,25,20],...
        'String','>>',...
        'Visible','off',...
        'Interruptible','off',...
        'BusyAction','cancel',...
        'Callback',[plotinfo.myname,' nextsol']);
    %-------------------------------------------------animate select button
    plotinfo.animate_but=uicontrol(gcf,'Style','checkbox', ...
      'String','Animate?',...
      'Value',1,...
      'Position',[450,15,70,20]);
    %-------------------------------------------save data in window data area
    set(fig,'UserData',plotinfo);
    %----------------------Load data from txt file 
    load_data()
    %----------------------draw intial plot
    initial_coords=[str2num(get(plotinfo.plat1x,'String')),str2num(get(plotinfo.plat1y,'String')),111.31-str2num(get(plotinfo.Pzval,'String')),...
                    str2num(get(plotinfo.plat2x,'String')),str2num(get(plotinfo.plat2y,'String')),111.31-str2num(get(plotinfo.Pzval,'String')),...
                    str2num(get(plotinfo.plat3x,'String')),str2num(get(plotinfo.plat3y,'String')),111.31-str2num(get(plotinfo.Pzval,'String')),...
                    str2num(get(plotinfo.plat4x,'String')),str2num(get(plotinfo.plat4y,'String')),111.31-str2num(get(plotinfo.Pzval,'String')),...
                    str2num(get(plotinfo.plat5x,'String')),str2num(get(plotinfo.plat5y,'String')),111.31-str2num(get(plotinfo.Pzval,'String')),...
                    str2num(get(plotinfo.plat6x,'String')),str2num(get(plotinfo.plat6y,'String')),111.31-str2num(get(plotinfo.Pzval,'String'))];
    draw_plat(initial_coords)
    view([-45,35])
    
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  Callbacks  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

case 'solve_for'
    plotinfo=get(gcf,'UserData');
    color_input_box(1);
    set(plotinfo.sol_for,'String','Working...');
    pause(1)
    solve_forward();    
    set(plotinfo.sol_for,'String','Solve Forward');
    
case 'solve_inv'
    plotinfo=get(gcf,'UserData');
    color_input_box(2);
    set(plotinfo.prevsol,'Visible','off')
    set(plotinfo.nextsol,'Visible','off')
    set(plotinfo.solutions_text,'Visible','off')
    set(plotinfo.sol_inv,'String','Working...');
    pause(1)
    solve_inverse();
    set(plotinfo.sol_inv,'String','Solve Inverse');

case 'prevsol'
    plotinfo=get(gcf,'UserData');
    if plotinfo.current_solution > 1
        plotinfo.current_solution=plotinfo.current_solution-1;
        set(plotinfo.roll,'String',double(plotinfo.solutions(plotinfo.current_solution,1)))%set roll/pitch/yaw fields to first solution
        set(plotinfo.pitch,'String',double(plotinfo.solutions(plotinfo.current_solution,2)))
        set(plotinfo.yaw,'String',double(plotinfo.solutions(plotinfo.current_solution,3)))
        set(plotinfo.Pxval,'String',double(plotinfo.solutions(plotinfo.current_solution,4)))
        set(plotinfo.Pyval,'String',double(plotinfo.solutions(plotinfo.current_solution,5)))
        set(plotinfo.Pzval,'String',double(plotinfo.solutions(plotinfo.current_solution,6)))
        set(plotinfo.nextsol,'Visible','on')
    end
    if plotinfo.current_solution==1
        set(plotinfo.prevsol,'Visible','off')
    end
    solve_inverse()
    set(gcf,'UserData',plotinfo);
    
case 'nextsol'
    plotinfo=get(gcf,'UserData');
    if plotinfo.current_solution < plotinfo.num_solutions
        plotinfo.current_solution=plotinfo.current_solution+1;
        set(plotinfo.roll,'String',double(plotinfo.solutions(plotinfo.current_solution,1)))%set roll/pitch/yaw fields to first solution
        set(plotinfo.pitch,'String',double(plotinfo.solutions(plotinfo.current_solution,2)))
        set(plotinfo.yaw,'String',double(plotinfo.solutions(plotinfo.current_solution,3)))
        set(plotinfo.Pxval,'String',double(plotinfo.solutions(plotinfo.current_solution,4)))
        set(plotinfo.Pyval,'String',double(plotinfo.solutions(plotinfo.current_solution,5)))
        set(plotinfo.Pzval,'String',double(plotinfo.solutions(plotinfo.current_solution,6)))
        set(plotinfo.prevsol,'Visible','on')
    end
    if plotinfo.current_solution == plotinfo.num_solutions
        set(plotinfo.nextsol,'Visible','off')
    end
    solve_inverse()
    set(gcf,'UserData',plotinfo);
        
case 'base'
    %disp('base')
case 'plat'
    %disp('plat')
case 'legs'
    color_input_box(1)
    %disp('legs')
case 'constraints'
    %disp('constraints')
case 'tablepos'
    color_input_box(2)
    %disp('tablepos')
case 'save_me'
    save_data()  
case 'quit'
   disp('quit')
   fig = gcf;
   quit_reply = questdlg('Are you sure you want to quit?');
   if strcmp(quit_reply,'Yes')
      save_data()
      close(fig);
   end    
   
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    FUNCTIONS    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    function pos = centerfig(width,height)
        screen_s = get(0,'ScreenSize');
        pos = [screen_s(3)/2 - width/2, screen_s(4)/2 - height/2, width, height];


    function save_data()
        plotinfo=get(gcf,'UserData'); %load form data into plotinfo 
        base=[str2num(get(plotinfo.base1x,'String')) %save all the info for save to file
              str2num(get(plotinfo.base1y,'String'))
              str2num(get(plotinfo.base2x,'String')) 
              str2num(get(plotinfo.base2y,'String'))
              str2num(get(plotinfo.base3x,'String')) 
              str2num(get(plotinfo.base3y,'String'))
              str2num(get(plotinfo.base4x,'String')) 
              str2num(get(plotinfo.base4y,'String'))
              str2num(get(plotinfo.base5x,'String')) 
              str2num(get(plotinfo.base5y,'String'))
              str2num(get(plotinfo.base6x,'String')) 
              str2num(get(plotinfo.base6y,'String'))];
        plat=[str2num(get(plotinfo.plat1x,'String')) 
              str2num(get(plotinfo.plat1y,'String'))
              str2num(get(plotinfo.plat2x,'String')) 
              str2num(get(plotinfo.plat2y,'String'))
              str2num(get(plotinfo.plat3x,'String')) 
              str2num(get(plotinfo.plat3y,'String'))
              str2num(get(plotinfo.plat4x,'String')) 
              str2num(get(plotinfo.plat4y,'String'))
              str2num(get(plotinfo.plat5x,'String')) 
              str2num(get(plotinfo.plat5y,'String'))
              str2num(get(plotinfo.plat6x,'String')) 
              str2num(get(plotinfo.plat6y,'String'))];
        cnst=[str2num(get(plotinfo.rollmin,'String')) 
              str2num(get(plotinfo.rollmax,'String'))
              str2num(get(plotinfo.pitchmin,'String')) 
              str2num(get(plotinfo.pitchmax,'String'))
              str2num(get(plotinfo.yawmin,'String')) 
              str2num(get(plotinfo.yawmax,'String'))
              str2num(get(plotinfo.pxmin,'String')) 
              str2num(get(plotinfo.pxmax,'String'))
              str2num(get(plotinfo.pymin,'String')) 
              str2num(get(plotinfo.pymax,'String'))
              str2num(get(plotinfo.pzmin,'String')) 
              str2num(get(plotinfo.pzmax,'String'))];
        legs=[str2num(get(plotinfo.leg1,'String'))
              str2num(get(plotinfo.leg2,'String'))
              str2num(get(plotinfo.leg3,'String'))
              str2num(get(plotinfo.leg4,'String'))
              str2num(get(plotinfo.leg5,'String'))
              str2num(get(plotinfo.leg6,'String'))];
        outs=[str2num(get(plotinfo.roll,'String'))
              str2num(get(plotinfo.pitch,'String'))
              str2num(get(plotinfo.yaw,'String'))
              str2num(get(plotinfo.Pxval,'String'))
              str2num(get(plotinfo.Pyval,'String'))
              str2num(get(plotinfo.Pzval,'String'))];
        save formdata.txt base plat cnst legs outs -ascii;%write all this to the file


    function load_data()
         load formdata.txt
         plotinfo=get(gcf,'UserData');
            set(plotinfo.base1x,'String',formdata(1))
            set(plotinfo.base1y,'String',formdata(2))
            set(plotinfo.base2x,'String',formdata(3))
            set(plotinfo.base2y,'String',formdata(4))
            set(plotinfo.base3x,'String',formdata(5))
            set(plotinfo.base3y,'String',formdata(6))
            set(plotinfo.base4x,'String',formdata(7))
            set(plotinfo.base4y,'String',formdata(8))
            set(plotinfo.base5x,'String',formdata(9))
            set(plotinfo.base5y,'String',formdata(10))
            set(plotinfo.base6x,'String',formdata(11))
            set(plotinfo.base6y,'String',formdata(12))
            set(plotinfo.plat1x,'String',formdata(13))
            set(plotinfo.plat1y,'String',formdata(14))
            set(plotinfo.plat2x,'String',formdata(15))
            set(plotinfo.plat2y,'String',formdata(16))
            set(plotinfo.plat3x,'String',formdata(17))
            set(plotinfo.plat3y,'String',formdata(18))
            set(plotinfo.plat4x,'String',formdata(19))
            set(plotinfo.plat4y,'String',formdata(20))
            set(plotinfo.plat5x,'String',formdata(21))
            set(plotinfo.plat5y,'String',formdata(22))
            set(plotinfo.plat6x,'String',formdata(23))
            set(plotinfo.plat6y,'String',formdata(24))
            set(plotinfo.rollmin,'String',formdata(25))
            set(plotinfo.rollmax,'String',formdata(26))
            set(plotinfo.pitchmin,'String',formdata(27))
            set(plotinfo.pitchmax,'String',formdata(28))
            set(plotinfo.yawmin,'String',formdata(29))
            set(plotinfo.yawmax,'String',formdata(30))
            set(plotinfo.pxmin,'String',formdata(31))
            set(plotinfo.pxmax,'String',formdata(32))
            set(plotinfo.pymin,'String',formdata(33))
            set(plotinfo.pymax,'String',formdata(34))
            set(plotinfo.pzmin,'String',formdata(35))
            set(plotinfo.pzmax,'String',formdata(36))
            set(plotinfo.leg1,'String',formdata(37))
            set(plotinfo.leg2,'String',formdata(38))
            set(plotinfo.leg3,'String',formdata(39))
            set(plotinfo.leg4,'String',formdata(40))
            set(plotinfo.leg5,'String',formdata(41))
            set(plotinfo.leg6,'String',formdata(42))
            set(plotinfo.roll,'String',formdata(43))
            set(plotinfo.pitch,'String',formdata(44))
            set(plotinfo.yaw,'String',formdata(45))
            set(plotinfo.Pxval,'String',formdata(46))
            set(plotinfo.Pyval,'String',formdata(47))
            set(plotinfo.Pzval,'String',formdata(48))


    function draw_plat(plat_coords)
        cla
        hold on
        axis vis3d
        plotinfo=get(gcf,'UserData');
            a1=[str2num(get(plotinfo.base1x,'String')); str2num(get(plotinfo.base1y,'String')); 0; 1];
            a2=[str2num(get(plotinfo.base2x,'String')); str2num(get(plotinfo.base2y,'String')); 0; 1];
            a3=[str2num(get(plotinfo.base3x,'String')); str2num(get(plotinfo.base3y,'String')); 0; 1];
            a4=[str2num(get(plotinfo.base4x,'String')); str2num(get(plotinfo.base4y,'String')); 0; 1];
            a5=[str2num(get(plotinfo.base5x,'String')); str2num(get(plotinfo.base5y,'String')); 0; 1];
            a6=[str2num(get(plotinfo.base6x,'String')); str2num(get(plotinfo.base6y,'String')); 0; 1];

            b1=[plat_coords(1); plat_coords(2); plat_coords(3); 1];
            b2=[plat_coords(4); plat_coords(5); plat_coords(6); 1];
            b3=[plat_coords(7); plat_coords(8); plat_coords(9); 1];
            b4=[plat_coords(10); plat_coords(11); plat_coords(12); 1];
            b5=[plat_coords(13); plat_coords(14); plat_coords(15); 1];
            b6=[plat_coords(16); plat_coords(17); plat_coords(18); 1];
            line_size=3;
            %neutral point
                plot3([0 0],[0 0],[0 111.31],'-ob','MarkerSize',3,'linewidth',line_size)
            %base
                plot3([a2(1) a3(1)],[a2(2) a3(2)],[0 0],'-b','MarkerSize',6,'linewidth',line_size);
                plot3([a4(1) a5(1)],[a4(2) a5(2)],[0 0],'-b','MarkerSize',6,'linewidth',line_size);
                plot3([a6(1) a1(1)],[a6(2) a1(2)],[0 0],'-b','MarkerSize',6,'linewidth',line_size);
            %legs
                plotinfo.p1=plot3([a1(1) b1(1)],[a1(2) b1(2)],[a1(3) b1(3)],'-.k','MarkerSize',6,'linewidth',line_size,'EraseMode','none');
                plotinfo.p2=plot3([a2(1) b2(1)],[a2(2) b2(2)],[a2(3) b2(3)],'-k','MarkerSize',6,'linewidth',line_size);
                plotinfo.p3=plot3([a3(1) b3(1)],[a3(2) b3(2)],[a3(3) b3(3)],'-k','MarkerSize',6,'linewidth',line_size);
                plotinfo.p4=plot3([a4(1) b4(1)],[a4(2) b4(2)],[a4(3) b4(3)],'-k','MarkerSize',6,'linewidth',line_size);
                plotinfo.p5=plot3([a5(1) b5(1)],[a5(2) b5(2)],[a5(3) b5(3)],'-k','MarkerSize',6,'linewidth',line_size);
                plotinfo.p6=plot3([a6(1) b6(1)],[a6(2) b6(2)],[a6(3) b6(3)],'-k','MarkerSize',6,'linewidth',line_size);
            %platform
                plotinfo.p7=plot3([b1(1) b2(1)],[b1(2) b2(2)],[b1(3) b2(3)],'-r','MarkerSize',6,'linewidth',line_size);
                plotinfo.p8=plot3([b2(1) b3(1)],[b2(2) b3(2)],[b2(3) b3(3)],'-r','MarkerSize',6,'linewidth',line_size);
                plotinfo.p9=plot3([b3(1) b4(1)],[b3(2) b4(2)],[b3(3) b4(3)],'-r','MarkerSize',6,'linewidth',line_size);
                plotinfo.p10=plot3([b4(1) b5(1)],[b4(2) b5(2)],[b4(3) b5(3)],'-r','MarkerSize',6,'linewidth',line_size);
                plotinfo.p11=plot3([b5(1) b6(1)],[b5(2) b6(2)],[b5(3) b6(3)],'-r','MarkerSize',6,'linewidth',line_size);
                plotinfo.p12=plot3([b6(1) b1(1)],[b6(2) b1(2)],[b6(3) b1(3)],'-r','MarkerSize',6,'linewidth',line_size);
            rotate3d
            set(gcf,'UserData',plotinfo)



    function anim_plat(plat_coords)
        plotinfo=get(gcf,'UserData');
        p1xold=get(plotinfo.p1,'XData');
        p2xold=get(plotinfo.p2,'XData');
        p3xold=get(plotinfo.p3,'XData');
        p4xold=get(plotinfo.p4,'XData');
        p5xold=get(plotinfo.p5,'XData');
        p6xold=get(plotinfo.p6,'XData');
        p7xold=get(plotinfo.p7,'XData');
        p8xold=get(plotinfo.p8,'XData');
        p9xold=get(plotinfo.p9,'XData');
        p10xold=get(plotinfo.p10,'XData');
        p11xold=get(plotinfo.p11,'XData');
        p12xold=get(plotinfo.p12,'XData');

        p1yold=get(plotinfo.p1,'YData');
        p2yold=get(plotinfo.p2,'YData');
        p3yold=get(plotinfo.p3,'YData');
        p4yold=get(plotinfo.p4,'YData');
        p5yold=get(plotinfo.p5,'YData');
        p6yold=get(plotinfo.p6,'YData');
        p7yold=get(plotinfo.p7,'YData');
        p8yold=get(plotinfo.p8,'YData');
        p9yold=get(plotinfo.p9,'YData');
        p10yold=get(plotinfo.p10,'YData');
        p11yold=get(plotinfo.p11,'YData');
        p12yold=get(plotinfo.p12,'YData');

        p1zold=get(plotinfo.p1,'ZData');
        p2zold=get(plotinfo.p2,'ZData');
        p3zold=get(plotinfo.p3,'ZData');
        p4zold=get(plotinfo.p4,'ZData');
        p5zold=get(plotinfo.p5,'ZData');
        p6zold=get(plotinfo.p6,'ZData');
        p7zold=get(plotinfo.p7,'ZData');
        p8zold=get(plotinfo.p8,'ZData');
        p9zold=get(plotinfo.p9,'ZData');
        p10zold=get(plotinfo.p10,'ZData');
        p11zold=get(plotinfo.p11,'ZData');
        p12zold=get(plotinfo.p12,'ZData');
        n=40;
        for i=1:n
            drawnow
            xp1 =[p1xold(1) (p1xold(2)+(plat_coords(1)-p1xold(2))/n*i)];
            yp1 =[p1yold(1) (p1yold(2)+(plat_coords(2)-p1yold(2))/n*i)];
            zp1 =[p1zold(1) (p1zold(2)+(plat_coords(3)-p1zold(2))/n*i)];
            xp2 =[p2xold(1) (p2xold(2)+(plat_coords(4)-p2xold(2))/n*i)];
            yp2 =[p2yold(1) (p2yold(2)+(plat_coords(5)-p2yold(2))/n*i)];
            zp2 =[p2zold(1) (p2zold(2)+(plat_coords(6)-p2zold(2))/n*i)];
            xp3 =[p3xold(1) (p3xold(2)+(plat_coords(7)-p3xold(2))/n*i)];
            yp3 =[p3yold(1) (p3yold(2)+(plat_coords(8)-p3yold(2))/n*i)];
            zp3 =[p3zold(1) (p3zold(2)+(plat_coords(9)-p3zold(2))/n*i)];
            xp4 =[p4xold(1) (p4xold(2)+(plat_coords(10)-p4xold(2))/n*i)];
            yp4 =[p4yold(1) (p4yold(2)+(plat_coords(11)-p4yold(2))/n*i)];
            zp4 =[p4zold(1) (p4zold(2)+(plat_coords(12)-p4zold(2))/n*i)];
            xp5 =[p5xold(1) (p5xold(2)+(plat_coords(13)-p5xold(2))/n*i)];
            yp5 =[p5yold(1) (p5yold(2)+(plat_coords(14)-p5yold(2))/n*i)];
            zp5 =[p5zold(1) (p5zold(2)+(plat_coords(15)-p5zold(2))/n*i)];
            xp6 =[p6xold(1) (p6xold(2)+(plat_coords(16)-p6xold(2))/n*i)];
            yp6 =[p6yold(1) (p6yold(2)+(plat_coords(17)-p6yold(2))/n*i)];
            zp6 =[p6zold(1) (p6zold(2)+(plat_coords(18)-p6zold(2))/n*i)];

            xp7 =[(p7xold(1)+(plat_coords(1)-p7xold(1))/n*i) (p7xold(2)+(plat_coords(4)-p7xold(2))/n*i)];
            yp7 =[(p7yold(1)+(plat_coords(2)-p7yold(1))/n*i) (p7yold(2)+(plat_coords(5)-p7yold(2))/n*i)];
            zp7 =[(p7zold(1)+(plat_coords(3)-p7zold(1))/n*i) (p7zold(2)+(plat_coords(6)-p7zold(2))/n*i)];
            xp8 =[(p8xold(1)+(plat_coords(4)-p8xold(1))/n*i) (p8xold(2)+(plat_coords(7)-p8xold(2))/n*i)];
            yp8 =[(p8yold(1)+(plat_coords(5)-p8yold(1))/n*i) (p8yold(2)+(plat_coords(8)-p8yold(2))/n*i)];
            zp8 =[(p8zold(1)+(plat_coords(6)-p8zold(1))/n*i) (p8zold(2)+(plat_coords(9)-p8zold(2))/n*i)];
            xp9 =[(p9xold(1)+(plat_coords(7)-p9xold(1))/n*i) (p9xold(2)+(plat_coords(10)-p9xold(2))/n*i)];
            yp9 =[(p9yold(1)+(plat_coords(8)-p9yold(1))/n*i) (p9yold(2)+(plat_coords(11)-p9yold(2))/n*i)];
            zp9 =[(p9zold(1)+(plat_coords(9)-p9zold(1))/n*i) (p9zold(2)+(plat_coords(12)-p9zold(2))/n*i)];
            xp10=[(p10xold(1)+(plat_coords(10)-p10xold(1))/n*i) (p10xold(2)+(plat_coords(13)-p10xold(2))/n*i)];
            yp10=[(p10yold(1)+(plat_coords(11)-p10yold(1))/n*i) (p10yold(2)+(plat_coords(14)-p10yold(2))/n*i)];
            zp10=[(p10zold(1)+(plat_coords(12)-p10zold(1))/n*i) (p10zold(2)+(plat_coords(15)-p10zold(2))/n*i)];
            xp11=[(p11xold(1)+(plat_coords(13)-p11xold(1))/n*i) (p11xold(2)+(plat_coords(16)-p11xold(2))/n*i)];
            yp11=[(p11yold(1)+(plat_coords(14)-p11yold(1))/n*i) (p11yold(2)+(plat_coords(17)-p11yold(2))/n*i)];
            zp11=[(p11zold(1)+(plat_coords(15)-p11zold(1))/n*i) (p11zold(2)+(plat_coords(18)-p11zold(2))/n*i)];
            xp12=[(p12xold(1)+(plat_coords(16)-p12xold(1))/n*i) (p12xold(2)+(plat_coords(1)-p12xold(2))/n*i)];
            yp12=[(p12yold(1)+(plat_coords(17)-p12yold(1))/n*i) (p12yold(2)+(plat_coords(2)-p12yold(2))/n*i)];
            zp12=[(p12zold(1)+(plat_coords(18)-p12zold(1))/n*i) (p12zold(2)+(plat_coords(3)-p12zold(2))/n*i)];

            set(plotinfo.p1,'XData',xp1,'YData',yp1,'ZData',zp1)
            set(plotinfo.p2,'XData',xp2,'YData',yp2,'ZData',zp2)
            set(plotinfo.p3,'XData',xp3,'YData',yp3,'ZData',zp3)
            set(plotinfo.p4,'XData',xp4,'YData',yp4,'ZData',zp4)
            set(plotinfo.p5,'XData',xp5,'YData',yp5,'ZData',zp5)
            set(plotinfo.p6,'XData',xp6,'YData',yp6,'ZData',zp6)
            set(plotinfo.p7,'XData',xp7,'YData',yp7,'ZData',zp7)
            set(plotinfo.p8,'XData',xp8,'YData',yp8,'ZData',zp8)
            set(plotinfo.p9,'XData',xp9,'YData',yp9,'ZData',zp9)
            set(plotinfo.p10,'XData',xp10,'YData',yp10,'ZData',zp10)
            set(plotinfo.p11,'XData',xp11,'YData',yp11,'ZData',zp11)
            set(plotinfo.p12,'XData',xp12,'YData',yp12,'ZData',zp12)
        end
            set(gcf,'UserData',plotinfo) 





    function platpos=save_plat_position()
        plotinfo=get(gcf,'UserData');
            old_plat_coord=[str2num(get(plotinfo.plat1x,'String'));
                            str2num(get(plotinfo.plat1y,'String'));
                            str2num(get(plotinfo.plat2x,'String'));
                            str2num(get(plotinfo.plat2y,'String'));
                            str2num(get(plotinfo.plat3x,'String'));
                            str2num(get(plotinfo.plat3y,'String'));
                            str2num(get(plotinfo.plat4x,'String'));
                            str2num(get(plotinfo.plat4y,'String'));
                            str2num(get(plotinfo.plat5x,'String'));
                            str2num(get(plotinfo.plat5y,'String'));
                            str2num(get(plotinfo.plat6x,'String'));
                            str2num(get(plotinfo.plat6y,'String'))];
        platpos=old_plat_coord;


    function color_input_box(BOX_IN)
        plotinfo=get(gcf,'UserData');
        if BOX_IN==1
            set(plotinfo.leg1,'BackgroundColor',[.8,1,1])
            set(plotinfo.leg2,'BackgroundColor',[.8,1,1])
            set(plotinfo.leg3,'BackgroundColor',[.8,1,1])
            set(plotinfo.leg4,'BackgroundColor',[.8,1,1])
            set(plotinfo.leg5,'BackgroundColor',[.8,1,1])
            set(plotinfo.leg6,'BackgroundColor',[.8,1,1])
            set(plotinfo.roll,'BackgroundColor',[1,1,1])
            set(plotinfo.pitch,'BackgroundColor',[1,1,1])
            set(plotinfo.yaw,'BackgroundColor',[1,1,1])
            set(plotinfo.Pxval,'BackgroundColor',[1,1,1])
            set(plotinfo.Pyval,'BackgroundColor',[1,1,1])
            set(plotinfo.Pzval,'BackgroundColor',[1,1,1])
        elseif BOX_IN==2
            set(plotinfo.leg1,'BackgroundColor',[1,1,1])
            set(plotinfo.leg2,'BackgroundColor',[1,1,1])
            set(plotinfo.leg3,'BackgroundColor',[1,1,1])
            set(plotinfo.leg4,'BackgroundColor',[1,1,1])
            set(plotinfo.leg5,'BackgroundColor',[1,1,1])
            set(plotinfo.leg6,'BackgroundColor',[1,1,1])
            set(plotinfo.roll,'BackgroundColor',[.8,1,1])
            set(plotinfo.pitch,'BackgroundColor',[.8,1,1])
            set(plotinfo.yaw,'BackgroundColor',[.8,1,1])
            set(plotinfo.Pxval,'BackgroundColor',[.8,1,1])
            set(plotinfo.Pyval,'BackgroundColor',[.8,1,1])
            set(plotinfo.Pzval,'BackgroundColor',[.8,1,1])
        end

    function solve_forward()
            plotinfo=get(gcf,'UserData');
            L1=str2num(get(plotinfo.leg1,'String'));
            L2=str2num(get(plotinfo.leg2,'String'));
            L3=str2num(get(plotinfo.leg3,'String'));
            L4=str2num(get(plotinfo.leg4,'String'));
            L5=str2num(get(plotinfo.leg5,'String'));
            L6=str2num(get(plotinfo.leg6,'String'));
            xsi=[str2num(get(plotinfo.base1x,'String')),...
                 str2num(get(plotinfo.base2x,'String')),...
                 str2num(get(plotinfo.base3x,'String')),...
                 str2num(get(plotinfo.base4x,'String')),...
                 str2num(get(plotinfo.base5x,'String')),...
                 str2num(get(plotinfo.base6x,'String'))];
            ysi=[str2num(get(plotinfo.base1y,'String')),...
                 str2num(get(plotinfo.base2y,'String')),...
                 str2num(get(plotinfo.base3y,'String')),...
                 str2num(get(plotinfo.base4y,'String')),...
                 str2num(get(plotinfo.base5y,'String')),...
                 str2num(get(plotinfo.base6y,'String'))];
            xmi=[str2num(get(plotinfo.plat1x,'String')),...
                 str2num(get(plotinfo.plat2x,'String')),...
                 str2num(get(plotinfo.plat3x,'String')),...
                 str2num(get(plotinfo.plat4x,'String')),...
                 str2num(get(plotinfo.plat5x,'String')),...
                 str2num(get(plotinfo.plat6x,'String'))];
            ymi=[str2num(get(plotinfo.plat1y,'String')),...
                 str2num(get(plotinfo.plat2y,'String')),...
                 str2num(get(plotinfo.plat3y,'String')),...
                 str2num(get(plotinfo.plat4y,'String')),...
                 str2num(get(plotinfo.plat5y,'String')),...
                 str2num(get(plotinfo.plat6y,'String'))];
            rollmin=str2num(get(plotinfo.rollmin,'String'));
            rollmax=str2num(get(plotinfo.rollmax,'String'));
            pitchmin=str2num(get(plotinfo.pitchmin,'String'));
            pitchmax=str2num(get(plotinfo.pitchmax,'String'));
            yawmin=str2num(get(plotinfo.yawmin,'String'));
            yawmax=str2num(get(plotinfo.yawmax,'String'));
            pxmin=str2num(get(plotinfo.pxmin,'String'));
            pxmax=str2num(get(plotinfo.pxmax,'String'));
            pymin=str2num(get(plotinfo.pymin,'String'));
            pymax=str2num(get(plotinfo.pymax,'String'));
            pzmin=str2num(get(plotinfo.pzmin,'String'));
            pzmax=str2num(get(plotinfo.pzmax,'String'));

            forward_solution=stew_forward(L1,L2,L3,L4,L5,L6,xsi,ysi,xmi,ymi,rollmin,rollmax,pitchmin,pitchmax,yawmin,yawmax,pxmin,pxmax,pymin,pymax,pzmin,pzmax);%this is an external function

            plotinfo.num_solutions=size(forward_solution,1);

            for i=size(forward_solution,1):-1:1
                plotinfo.solutions(i,:)=forward_solution(i,:);
            end
            set(plotinfo.roll,'String',double(plotinfo.solutions(1,1)))%set roll/pitch/yaw fields to first solution
            set(plotinfo.pitch,'String',double(plotinfo.solutions(1,2)))
            set(plotinfo.yaw,'String',double(plotinfo.solutions(1,3)))
            set(plotinfo.Pxval,'String',double(plotinfo.solutions(1,4)))
            set(plotinfo.Pyval,'String',double(plotinfo.solutions(1,5)))
            set(plotinfo.Pzval,'String',double(plotinfo.solutions(1,6)))

            if plotinfo.num_solutions==1
                set(plotinfo.prevsol,'Visible','off')
                set(plotinfo.nextsol,'Visible','off')
                set(plotinfo.solutions_text,'Visible','off')
            else
                set(plotinfo.prevsol,'Visible','off')
                set(plotinfo.nextsol,'Visible','on')
                solutions_text=[num2str(plotinfo.num_solutions),' Solutions',];
                set(plotinfo.solutions_text,'String',solutions_text,'Visible','on')
            end
            plotinfo.current_solution=1;
            set(gcf,'UserData',plotinfo);  %save changed values to data area 
            solve_inverse() 

    function solve_inverse()
            plotinfo=get(gcf,'UserData');
            xsi=[str2num(get(plotinfo.base1x,'String')),...
                 str2num(get(plotinfo.base2x,'String')),...
                 str2num(get(plotinfo.base3x,'String')),...
                 str2num(get(plotinfo.base4x,'String')),...
                 str2num(get(plotinfo.base5x,'String')),...
                 str2num(get(plotinfo.base6x,'String'))];
            ysi=[str2num(get(plotinfo.base1y,'String')),...
                 str2num(get(plotinfo.base2y,'String')),...
                 str2num(get(plotinfo.base3y,'String')),...
                 str2num(get(plotinfo.base4y,'String')),...
                 str2num(get(plotinfo.base5y,'String')),...
                 str2num(get(plotinfo.base6y,'String'))];
            xmi=[str2num(get(plotinfo.plat1x,'String')),...
                 str2num(get(plotinfo.plat2x,'String')),...
                 str2num(get(plotinfo.plat3x,'String')),...
                 str2num(get(plotinfo.plat4x,'String')),...
                 str2num(get(plotinfo.plat5x,'String')),...
                 str2num(get(plotinfo.plat6x,'String'))];
            ymi=[str2num(get(plotinfo.plat1y,'String')),...
                 str2num(get(plotinfo.plat2y,'String')),...
                 str2num(get(plotinfo.plat3y,'String')),...
                 str2num(get(plotinfo.plat4y,'String')),...
                 str2num(get(plotinfo.plat5y,'String')),...
                 str2num(get(plotinfo.plat6y,'String'))];
             roll=str2num(get(plotinfo.roll,'String'));
             pitch=str2num(get(plotinfo.pitch,'String'));
             yaw=str2num(get(plotinfo.yaw,'String'));
             px=str2num(get(plotinfo.Pxval,'String'));
             py=str2num(get(plotinfo.Pyval,'String'));
             pz=str2num(get(plotinfo.Pzval,'String'));

             inverse_solution=stew_inverse(xsi,ysi,xmi,ymi,roll,pitch,yaw,px,py,pz);

             set(plotinfo.leg1,'String',double(inverse_solution(1)));
             set(plotinfo.leg2,'String',double(inverse_solution(2)));
             set(plotinfo.leg3,'String',double(inverse_solution(3)));
             set(plotinfo.leg4,'String',double(inverse_solution(4)));
             set(plotinfo.leg5,'String',double(inverse_solution(5)));
             set(plotinfo.leg6,'String',double(inverse_solution(6)));

             plat_coords=inverse_solution(25:42);
             anim_state=get(plotinfo.animate_but,'Value');
             if anim_state==0
                draw_plat(plat_coords)
             elseif anim_state==1
                anim_plat(plat_coords)
             end